source=src
source-dir=src/app
test-dir=test/app
library=lib
build=bin
build-dir=bin/app
coverage-dir=coverage-report
google-format-jar-url=https://repo.maven.apache.org/maven2/com/google/googlejavaformat/google-java-format/1.13.0/google-java-format-1.13.0-all-deps.jar
google-format-jar=lib/google-java-format-1.13.0-all-deps.jar
junit-jar-url=https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
junit-jar=lib/junit-platform-console-standalone-1.8.2.jar
jacoco-agent-jar-url=https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar
jacoco-agent-jar=lib/org.jacoco.agent-0.8.7-runtime.jar
jacoco-cli-jar-url=https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.cli/0.8.7/org.jacoco.cli-0.8.7-nodeps.jar
jacoco-cli-jar=lib/org.jacoco.cli-0.8.7-nodeps.jar
package=app
