name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch and tags
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-26.04
    # This job will NOT run if a git tag is pushed
    if: "!startsWith(github.ref, 'refs/tags/')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Pull repo
        uses: actions/checkout@v7
      # Runs a set of commands using the runner's shell
      - name: Script
        run: |
          curl -LO https://repo.maven.apache.org/maven2/com/google/googlejavaformat/google-java-format/1.36.1/google-java-format-1.36.1-all-deps.jar
          java \
          --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
          --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
          --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
          --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
          --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
          --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
          --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
          --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
          --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
          --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED \
          -jar google-java-format-1.36.1-all-deps.jar src/app/*.java test/app/*.java

  Build:
    runs-on: ubuntu-26.04
    needs: Lint
    if: always() && (needs.Lint.result == 'success' || needs.Lint.result == 'skipped')
    steps:
      - name: Pull repo
        uses: actions/checkout@v7
      - name: Script
        run: javac -d bin src/app/*.java
      - name: Cache build artifacts
        uses: actions/cache@v5
        id: build-artifacts
        with:
          path: bin
          key: ${{ runner.os }}-build-artifacts

  Test:
    needs: Build
    runs-on: ubuntu-26.04
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Pull repo
        uses: actions/checkout@v7
      - name: Download build artifacts
        uses: actions/cache@v5
        id: build-artifacts
        with:
          path: bin
          key: ${{ runner.os }}-build-artifacts
      - name: Script
        run: |
          curl -LO https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-console-standalone/1.14.4/junit-platform-console-standalone-1.14.4.jar
          javac -d bin -cp bin:junit-platform-console-standalone-1.14.4.jar test/app/*.java
          java -jar junit-platform-console-standalone-1.14.4.jar --class-path=bin --scan-classpath --fail-if-no-tests
      - name: Cache test artifacts
        id: test-artifacts
        uses: actions/cache@v5
        with:
          path: bin
          key: ${{ runner.os }}-test-artifacts
      - name: Cache junit jar
        id: junit-jar
        uses: actions/cache@v5
        with:
          path: junit-platform-console-standalone-1.14.4.jar
          key: ${{ runner.os }}-junit-jar

  Cover:
    needs: Test
    runs-on: ubuntu-26.04
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Pull repo
        uses: actions/checkout@v7
      - name: Download build artifacts
        uses: actions/cache@v5
        id: build-artifacts
        with:
          path: bin
          key: ${{ runner.os }}-build-artifacts
      - name: Download test artifacts
        uses: actions/cache@v5
        id: test-artifacts
        with:
          path: bin
          key: ${{ runner.os }}-test-artifacts
      - name: Download junit jar
        uses: actions/cache@v5
        id: junit-jar
        with:
          path: junit-platform-console-standalone-1.14.4.jar
          key: ${{ runner.os }}-junit-jar
      - name: Script
        run: |
          curl -LO https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.15/org.jacoco.agent-0.8.15-runtime.jar
          curl -LO https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.cli/0.8.15/org.jacoco.cli-0.8.15-nodeps.jar
          java -javaagent:org.jacoco.agent-0.8.15-runtime.jar -jar junit-platform-console-standalone-1.14.4.jar --class-path=bin --scan-classpath --fail-if-no-tests
          rm bin/app/*Test.class bin/app/Driver.class
          java -jar org.jacoco.cli-0.8.15-nodeps.jar report jacoco.exec --classfiles bin --sourcefiles src --html coverage-report
      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage-report

  Package:
    needs: Build
    runs-on: ubuntu-26.04
    if: always() && (needs.Build.result == 'success')
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Pull repo
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload static HTML pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: './public'
      - name: Deploy to GitHub Pages # https://chrislattman.github.io/blogging-project
        id: deployment
        uses: actions/deploy-pages@v5
      - name: Download build artifacts
        uses: actions/cache@v5
        id: build-artifacts
        with:
          path: bin
          key: ${{ runner.os }}-build-artifacts
      - name: Script
        run: |
          cd bin
          mkdir META-INF
          echo -e "Manifest-Version":" 1.0\nMain-Class":" app.Driver\n" > META-INF/MANIFEST.MF
          jar -cmf META-INF/MANIFEST.MF ../blogging-project.jar app/*.class
      - name: Upload jar
        uses: actions/upload-artifact@v7
        with:
          name: blogging-project.jar
          path: blogging-project.jar
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  Release:
    needs: Package
    runs-on: ubuntu-latest
    if: always() && (needs.Package.result == 'success')
    permissions:
      contents: write
    steps:
      - name: Pull repo
        uses: actions/checkout@v7
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            -n "Sample release for blogging project." \
            --generate-notes
